# Generated by Django 4.1 on 2022-08-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='roomname',
            new_name='room_id',
        ),
    ]
