# Generated by Django 4.1 on 2022-08-24 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_roomname_chatmessage_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='datetime',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='date',
            field=models.DateField(blank='True', default=datetime.date(2022, 8, 24)),
        ),
    ]
