# Generated by Django 4.1 on 2022-08-24 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmessage_datetime_chatmessage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='date',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='datetime',
            field=models.DateTimeField(blank='True', default=datetime.datetime.now),
        ),
    ]
